# Docker file for thedatabase image (MariaDB)
FROM mariadb:latest
# Set environment variables for the database (mariadb)
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=database_name
ENV MYSQL_USER=user_name
ENV MYSQL_PASSWORD=MYSQL_PASSWORD
# Expose the default MariaDB port
EXPOSE 3306